//! Build-time codegen: read the single source of truth (`../vocab.ron`) and emit
//! `OUT_DIR/vocab_gen.rs` — plain `no_std` Rust tables the core `include!`s. The .ron
//! stays the one place the vocabulary is authored; this is its projection into the core.
//!
//! Two invariants are enforced HERE, at build time (a violation fails the build, which is
//! even stronger than "refuse to boot"):
//!   * every verb's slots are pairwise-distinct in type (LANGUAGE.md §2);
//!   * every type-id / constant-id referenced by a verb or sampler actually exists.
//!
//! build-deps may use std freely; only the GENERATED code must stay no_std.

use serde::Deserialize;
use std::collections::BTreeSet;
use std::{env, fs, path::Path};

// NOTE: RON verifies struct names, so these MUST match the names used in vocab.ron
// (`Type(...)`, `Verb(...)`, `Const(...)`, `Colour(...)`, …). Unknown fields (nl/doc/examples)
// are ignored by serde.
#[derive(Deserialize)]
struct Vocab {
    types: Vec<Type>,
    verbs: Vec<Verb>,
    constants: Vec<Const>,
    colours: Vec<Colour>,
    oscillators: Vec<Osc>,
    envelopes: Vec<Env>,
    notes: Vec<Note>,
    keywords: Vec<Keyword>,
}

#[derive(Deserialize)]
struct Type { id: String, reserved: bool }

#[derive(Deserialize)]
struct Verb { id: String, slots: Vec<String>, sampler: Option<Sampler> }

#[derive(Deserialize)]
enum Sampler {
    Uniform { domain: String, lo: i64, hi: i64 },
    Choice { domain: String, of: Vec<String> },
}

#[derive(Deserialize)]
struct Const { id: String, #[serde(rename = "type")] ty: String, value: CValue }

#[derive(Deserialize)]
enum CValue { I(i64), Rest }

#[derive(Deserialize)]
struct Colour { id: String }
#[derive(Deserialize)]
struct Osc { id: String }
#[derive(Deserialize)]
struct Env { id: String }

#[derive(Deserialize)]
struct Note { id: String, freq_hz: f64 }

#[derive(Deserialize)]
struct Keyword { id: String, kind: KwKind }

#[derive(Deserialize, Clone, Copy)]
enum KwKind { Maak, Print, Loop, LoopAux, If, Else, Compare, WrapMode, Break }

/// Map a vocab type-id string to the core `Type` enum variant path. Panics on an unknown
/// id so a typo in the spec fails the build instead of silently dropping a slot.
fn type_variant(id: &str) -> &'static str {
    match id {
        "schildpad" => "Type::Schildpad",
        "getal" => "Type::Getal",
        "draairichting" => "Type::Draairichting",
        "toon" => "Type::Toon",
        "deuntje" => "Type::Deuntje",
        "kleur" => "Type::Kleur",
        "oscillator" => "Type::Oscillator",
        "omhullende" => "Type::Omhullende",
        "nil" => "Type::Nil",
        "tekst" => "Type::Tekst",
        other => panic!("vocab.ron: unknown type id `{other}` — add it to Type and build.rs::type_variant"),
    }
}

fn kw_variant(k: KwKind) -> &'static str {
    match k {
        KwKind::Maak => "KwKind::Maak",
        KwKind::Print => "KwKind::Print",
        KwKind::Loop => "KwKind::Loop",
        KwKind::LoopAux => "KwKind::LoopAux",
        KwKind::If => "KwKind::If",
        KwKind::Else => "KwKind::Else",
        KwKind::Compare => "KwKind::Compare",
        KwKind::WrapMode => "KwKind::WrapMode",
        KwKind::Break => "KwKind::Break",
    }
}

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let vocab_path = Path::new(&manifest).join("..").join("vocab.ron");
    println!("cargo:rerun-if-changed={}", vocab_path.display());

    let text = fs::read_to_string(&vocab_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", vocab_path.display()));
    let v: Vocab = ron::from_str(&text)
        .unwrap_or_else(|e| panic!("vocab.ron parse error: {e}"));

    // ---- validation ----------------------------------------------------------
    let type_ids: BTreeSet<&str> = v.types.iter().map(|t| t.id.as_str()).collect();
    let const_ids: std::collections::BTreeMap<&str, i64> = v
        .constants
        .iter()
        .filter_map(|c| match c.value { CValue::I(n) => Some((c.id.as_str(), n)), CValue::Rest => None })
        .collect();

    for vb in &v.verbs {
        // pairwise-distinct slot types (LANGUAGE.md §2)
        let mut seen = BTreeSet::new();
        for s in &vb.slots {
            if !type_ids.contains(s.as_str()) {
                panic!("vocab.ron: verb `{}` references unknown slot type `{}`", vb.id, s);
            }
            if !seen.insert(s.as_str()) {
                panic!(
                    "vocab.ron: verb `{}` declares two `{}` slots — pairwise-distinct slot \
                     types are required (LANGUAGE.md §2). Add an explicit positional tie-break \
                     before allowing this.",
                    vb.id, s
                );
            }
        }
    }

    // ---- codegen --------------------------------------------------------------
    let mut out = String::new();
    out.push_str("// @generated by build.rs from ../vocab.ron — do not edit.\n\n");

    // reserved type words
    out.push_str("pub const RESERVED_TYPE_WORDS: &[(&str, Type)] = &[\n");
    for t in v.types.iter().filter(|t| t.reserved) {
        out.push_str(&format!("    ({:?}, {}),\n", t.id, type_variant(&t.id)));
    }
    out.push_str("];\n\n");

    // verbs
    out.push_str("pub const VERBS: &[VerbSig] = &[\n");
    for vb in &v.verbs {
        let slots = vb
            .slots
            .iter()
            .map(|s| type_variant(s))
            .collect::<Vec<_>>()
            .join(", ");
        let sampler = match &vb.sampler {
            None => "None".to_string(),
            Some(Sampler::Uniform { domain, lo, hi }) => {
                assert_eq!(domain, "getal", "verb `{}`: only getal Uniform samplers supported", vb.id);
                format!("Some(Sampler::UniformGetal {{ lo: {lo}, hi: {hi} }})")
            }
            Some(Sampler::Choice { domain, of }) => match domain.as_str() {
                "draairichting" => {
                    let degs = of
                        .iter()
                        .map(|c| {
                            *const_ids.get(c.as_str()).unwrap_or_else(|| {
                                panic!("verb `{}`: sampler references unknown draairichting constant `{}`", vb.id, c)
                            })
                        })
                        .map(|n| (n as i32).to_string())
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!("Some(Sampler::ChoiceDraai(&[{degs}]))")
                }
                "toon" => {
                    let notes = of.iter().map(|n| format!("{n:?}")).collect::<Vec<_>>().join(", ");
                    format!("Some(Sampler::ChoiceNote(&[{notes}]))")
                }
                other => panic!("verb `{}`: unsupported Choice sampler domain `{}`", vb.id, other),
            },
        };
        out.push_str(&format!(
            "    VerbSig {{ name: {:?}, slots: &[{}], sampler: {} }},\n",
            vb.id, slots, sampler
        ));
    }
    out.push_str("];\n\n");

    // constants (id -> typed value)
    out.push_str("pub const CONSTANTS: &[(&str, ConstVal)] = &[\n");
    for c in &v.constants {
        if !type_ids.contains(c.ty.as_str()) {
            panic!("vocab.ron: constant `{}` has unknown type `{}`", c.id, c.ty);
        }
        let cv = match (&c.value, c.ty.as_str()) {
            (CValue::I(n), "draairichting") => format!("ConstVal::Draai({n})"),
            (CValue::I(n), "getal") => format!("ConstVal::Getal({n})"),
            (CValue::Rest, "toon") => "ConstVal::Rest".to_string(),
            (_, other) => panic!("constant `{}`: unsupported (value, type=`{}`) combination", c.id, other),
        };
        out.push_str(&format!("    ({:?}, {}),\n", c.id, cv));
    }
    out.push_str("];\n\n");

    emit_id_list(&mut out, "COLOURS", v.colours.iter().map(|c| c.id.as_str()));
    emit_id_list(&mut out, "OSCILLATORS", v.oscillators.iter().map(|c| c.id.as_str()));
    emit_id_list(&mut out, "ENVELOPES", v.envelopes.iter().map(|c| c.id.as_str()));

    out.push_str("pub const NOTES: &[(&str, f32)] = &[\n");
    for n in &v.notes {
        out.push_str(&format!("    ({:?}, {}f32),\n", n.id, n.freq_hz));
    }
    out.push_str("];\n\n");

    out.push_str("pub const KEYWORDS: &[(&str, KwKind)] = &[\n");
    for k in &v.keywords {
        out.push_str(&format!("    ({:?}, {}),\n", k.id, kw_variant(k.kind)));
    }
    out.push_str("];\n\n");

    // sin table, Q12 fixed-point (×4096), degrees 0..=90. Computed here with host f64 sin
    // and baked as integers so the RUNTIME does only integer math → identical on every
    // target (the determinism rule, ARCHITECTURE.md §10). Quadrant symmetry covers 0..360.
    out.push_str("pub const SIN_Q12: &[i32; 91] = &[\n    ");
    for deg in 0..=90 {
        let v = ((deg as f64).to_radians().sin() * 4096.0).round() as i32;
        out.push_str(&format!("{v}, "));
    }
    out.push_str("\n];\n");

    let out_dir = env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("vocab_gen.rs"), out).unwrap();
}

fn emit_id_list<'a>(out: &mut String, name: &str, ids: impl Iterator<Item = &'a str>) {
    out.push_str(&format!("pub const {name}: &[&str] = &["));
    out.push_str(&ids.map(|s| format!("{s:?}")).collect::<Vec<_>>().join(", "));
    out.push_str("];\n\n");
}
